# Build Stage
FROM node:16-alpine3.16 as build-stage

# Set working directory inside the container
WORKDIR /client

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production && \
    npm cache clean --force

# Copy application source code
COPY . .

# Build the application
RUN npm run build

# Production Stage
FROM nginx:1.23-alpine as production-stage

# Copy the built application from the build stage
COPY --from=build-stage /client/build /usr/share/nginx/html

# Expose the port for nginx
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
