# Set base image
FROM node:16-alpine3.16 

# Set working directory inside the container
WORKDIR /backend

# Copy package.json and package-lock.json to install dependencies
COPY packag*.json ./

# Install only prodction dependencies and clean up unnecessary files
RUN npm install --only=production && \
    npm cache clean --force

# Copy application source code
COPY . .

# Set environment variable for production but better to manage in Docker-compose file.
# ENV NODE_ENV=production

#Expose the port for the backend
EXPOSE 5000

# Start the backend server
CMD ["node", "start"]