---
- name: Pull image from docker repository 
  docker_image:
    name: tonui/tonui-yolo-backend:v1.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: tonui-yolo-backend
    image: tonui/tonui-yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes