---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  roles:
    - setup-mongodb       # First, set up the database.
    - backend-deployment  # Then, deploy the backend that needs the database.
    - frontend-deployment 
    