apiVersion: v1
kind: Service
metadata:
  name: yolo-client-service 
  labels:
    app: yolo-client
spec:
  type: LoadBalancer  # Expose the service publicly
  selector:
    app: yolo-client  # Match pods with this label
  ports:
  - port: 80  # External port exposed by the service
    targetPort: 80  # Port inside the container where Nginx is running
