apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
  labels:
    app: yolo-client
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client-container
        image: gcr.io/yolo-449108/tonui-yolo-client:v1.0.0 
        resources:
          limits:
            memory: "256Mi"  # Max memory limit
            cpu: "500m"  # Max CPU limit
          requests:
            memory: "128Mi"  # Guaranteed memory
            cpu: "250m"  # Guaranteed CPU
        ports:
        - containerPort: 80  # The container runs on port 80 as per the Nginx setup
