apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Request 1Gi of storage
  storageClassName: standard  # Matches the storage class of the PV
